# ==========================================================================
# CRE PROJECT SETTINGS FILE
# ==========================================================================

staging-settings:
  rpcs:
    - chain-name: ethereum-mainnet
      url: https://mainnet.infura.io/v3/d8eb43c52f284bb48ac977cfc22e7f9e

production-settings:
  rpcs:
    - chain-name: ethereum-mainnet
      url: https://mainnet.infura.io/v3/d8eb43c52f284bb48ac977cfc22e7f9e